security:
    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                login_path:  /login
                check_path:  /login_check
            security: true
            anonymous: true
            logout:
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

    providers:
            in_memory:
                memory:
                    users:
                        test:
                            password: test
                            roles: 'ROLE_USER'

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext

