home:
    path:     /
    defaults: { _controller: RedmineBundle:User:home }
login:
    pattern:   /login
    defaults:  { _controller: RedmineBundle:User:login }
login_check:
    pattern:   /login_check
_security_logout:
    pattern: /logout
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: /
      permanent: true

show_issue:
    path:     /project
    defaults: { _controller: RedmineBundle:Project:showIssue }

show_comment:
    path:     /comment
    defaults: { _controller: RedmineBundle:Comment:showComment }